/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.autolk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vidu
 */
public class ItemList extends javax.swing.JFrame {

    /**
     * Creates new form ItemList
     */
    public ItemList() {
        initComponents();  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genarate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SummeryTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        LowGen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lowTble = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Genarate.setText("Genarate");
        Genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenarateActionPerformed(evt);
            }
        });

        SummeryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Main Category", "Sub Category", "Number of in Stoke"
            }
        ));
        jScrollPane1.setViewportView(SummeryTbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sumery of Stoke");

        LowGen.setText("Genarate  Low Stoke Item");
        LowGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowGenActionPerformed(evt);
            }
        });

        lowTble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Avalable stoke", "Main Category", "Sub Category"
            }
        ));
        jScrollPane2.setViewportView(lowTble);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LowGen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Genarate)
                                .addGap(106, 106, 106)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Genarate)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LowGen))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenarateActionPerformed
        // TODO add your handling code here:
        
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/team012","root","");
            Statement stm = con.createStatement();
            
            String sql1="SELECT DISTINCT main_category FROM items";
       
            ResultSet rs1 = stm.executeQuery(sql1);
            
            while(rs1.next()){
                String mainCat =rs1.getString("main_category");
                //System.out.println(mainCat);
                Statement stm1 = con.createStatement();
                String sql2="SELECT COUNT(sub_category) AS Count,sub_category AS sub FROM items WHERE main_category='"+mainCat+"' GROUP BY sub_category";
                ResultSet rs2 = stm1.executeQuery(sql2);
                while(rs2.next()){
                    
                    String count=String.valueOf(rs2.getInt("Count"));
                    String subCat=rs2.getString("sub");
                    String tblData[]={mainCat,subCat,count};
                    DefaultTableModel tblModel =(DefaultTableModel)SummeryTbl.getModel();
                    tblModel.addRow(tblData);
                    
     
                    
                }
  
            }
            
         
            con.close();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_GenarateActionPerformed

    private void LowGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowGenActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/team012","root","");
            Statement stm = con.createStatement();
            
            String sql = "SELECT name,in_stock_item,main_category,sub_category FROM items WHERE in_stock_item<5 ORDER BY in_stock_item";
            
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()){
                String name =rs.getString("name");
                String items =String.valueOf(rs.getInt("in_stock_item"));
                String mainC =rs.getString("main_category");
                String subC =rs.getString("sub_category");
                
                String tblData[]={name,items,mainC,subC};
                DefaultTableModel tblModel =(DefaultTableModel)lowTble.getModel();
                tblModel.addRow(tblData);
                
                
                
            }
            
         
            con.close();
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_LowGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Genarate;
    private javax.swing.JButton LowGen;
    private javax.swing.JTable SummeryTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lowTble;
    // End of variables declaration//GEN-END:variables
}
